// initial state
const state = {
  selectedContractsId: 'contracts3',
  selectedContractId: 'contract5',
  contracts: {
    headers: [
      {
        text: '产品',
        align: 'left',
        value: 'product'
      },
      { text: '卖出数量', value: 'sellAmount', align: 'right'},
      { text: '卖出价', value: 'sellingPrice', align: 'right' },
      { text: '买入价', value: 'buyingPrice', align: 'right' },
      { text: '买入数量', value: 'buyAmount', align: 'right' },
      { text: '市价', value: 'marketPrice', align: 'right' },
      { text: '%', value: 'percent', align: 'right' },
      { text: '净涨跌', value: 'fallAndRaise', align: 'right' }
    ],
    data: {
      contracts1: [
        {
          id: 'contract1',
          value: false,
          product: 'UK 100',
          sellAmount: 0,
          sellingPrice: 6906.20,
          buyingPrice: 6906.500,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'TF9 • GBP'
        },
        {
          id: 'contract2',
          value: false,
          product: 'UK 100',
          sellAmount: 0,
          sellingPrice: 6906.20,
          buyingPrice: 6906.500,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'TF9 • GBP'
        },
      ],
      contracts2: [
        {
          id: 'contract3',
          value: false,
          product: 'CK Hutchison Holdings Ltd',
          sellAmount: 0,
          sellingPrice: 77.500,
          buyingPrice: 77.500,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'TF9 • GBP'
        },
        {
          id: 'contract4',
          value: false,
          product: 'CK Hutchison Holdings Ltd',
          sellAmount: 0,
          sellingPrice: 77.500,
          buyingPrice: 77.500,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'TF9 • GBP'
        },
      ],
      contracts3: [
        {
          id: 'contract15',
          value: false,
          product: 'XAU/USD',
          sellAmount: 0,
          sellingPrice: 1315.21,
          buyingPrice: 1314.84,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview12',
          description: 'BTC • USD'
        },
        {
          id: 'contract16',
          value: false,
          product: 'XAG/USD',
          sellAmount: 0,
          sellingPrice: 14.52,
          buyingPrice: 14.43,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview13',
          description: 'BTC • USD'
        },
        {
          id: 'contract17',
          value: false,
          product: 'AUX/CNY',
          sellAmount: 0,
          sellingPrice: 287.51,
          buyingPrice: 287.45,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview14',
          description: 'BTC • USD'
        },
        {
          id: 'contract18',
          value: false,
          product: 'AUY/CNY',
          sellAmount: 0,
          sellingPrice: 287.35,
          buyingPrice: 287.31,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview15',
          description: 'BTC • USD'
        },
      ],
      contracts4: [
        {
          id: 'contract5',
          value: false,
          product: 'BTC/USDT',
          sellAmount: 0,
          sellingPrice: 3632.52,
          buyingPrice: 3632.24,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'BTC • USD'
        },
        {
          id: 'contract6',
          value: false,
          product: 'ETH/USDT',
          sellAmount: 0,
          sellingPrice: 120.63,
          buyingPrice: 120.48,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview2',
          description: 'ETH • USD'
        },
        {
          id: 'contract9',
          value: false,
          product: 'LTC/USDT',
          sellAmount: 0,
          sellingPrice: 44.14,
          buyingPrice: 44.09,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview5',
          description: 'LTC • USD'
        },
        {
          id: 'contract7',
          value: false,
          product: 'EOS/USDT',
          sellAmount: 0,
          sellingPrice: 2.7544,
          buyingPrice: 2.7318,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview3',
          description: 'EOS • USD'
        },
        {
          id: 'contract19',
          value: false,
          product: 'XRP/USTD',
          sellAmount: 0,
          sellingPrice: 0.3025,
          buyingPrice: 0.3012,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview16',
          description: 'BTC • USD'
        },
        {
          id: 'contract20',
          value: false,
          product: 'DASH/USDT',
          sellAmount: 0,
          sellingPrice: 79.41,
          buyingPrice: 79.25,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview17',
          description: 'BTC • USD'
        },
        {
          id: 'contract10',
          value: false,
          product: 'BCH/USDT',
          sellAmount: 0,
          sellingPrice: 123.26,
          buyingPrice: 123.02,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview6',
          description: 'BCH • USD'
        },
        {
          id: 'contract21',
          value: false,
          product: 'BNB/USDT',
          sellAmount: 0,
          sellingPrice: 9.6275,
          buyingPrice: 9.6223,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview18',
          description: 'BTC • USD'
        },
        {
          id: 'contract22',
          value: false,
          product: 'ADA/USDT',
          sellAmount: 0,
          sellingPrice: 0.0421,
          buyingPrice: 0.0413,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview19',
          description: 'BTC • USD'
        },
        {
          id: 'contract12',
          value: false,
          product: 'BSV/USDT',
          sellAmount: 0,
          sellingPrice: 64.92,
          buyingPrice: 64.84,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview8',
          description: 'BSV • USD'
        },
      ],
      contracts5: [
        {
          id: 'contract23',
          value: false,
          product: 'USDT/BTC',
          sellAmount: 0,
          sellingPrice: 0.000275312,
          buyingPrice: 0.000275291,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview20',
          description: 'BTC • USD'
        },
        {
          id: 'contract24',
          value: false,
          product: 'ETH/BTC',
          sellAmount: 0,
          sellingPrice: 0.033209631,
          buyingPrice: 0.033168336,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview21',
          description: 'BTC • USD'
        },
        {
          id: 'contract25',
          value: false,
          product: 'LTC/BTC',
          sellAmount: 0,
          sellingPrice: 0.012151812,
          buyingPrice: 0.012138047,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview22',
          description: 'BTC • USD'
        },
        {
          id: 'contract26',
          value: false,
          product: 'EOS/BTC',
          sellAmount: 0,
          sellingPrice: 0.000758291,
          buyingPrice: 0.000752069,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview23',
          description: 'BTC • USD'
        },
        {
          id: 'contract27',
          value: false,
          product: 'XRP/BTC',
          sellAmount: 0,
          sellingPrice: 0.00008328,
          buyingPrice: 0.00008292,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview24',
          description: 'BTC • USD'
        },
        {
          id: 'contract28',
          value: false,
          product: 'DASH/BTC',
          sellAmount: 0,
          sellingPrice: 0.021861699,
          buyingPrice: 0.021817651,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview25',
          description: 'BTC • USD'
        },
        {
          id: 'contract29',
          value: false,
          product: 'BCH/BTC',
          sellAmount: 0,
          sellingPrice: 0.033933674,
          buyingPrice: 0.033867602,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview26',
          description: 'BTC • USD'
        },
        {
          id: 'contract30',
          value: false,
          product: 'BNB/BTC',
          sellAmount: 0,
          sellingPrice: 0.002650466,
          buyingPrice: 0.002649035,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview27',
          description: 'BTC • USD'
        },
        {
          id: 'contract31',
          value: false,
          product: 'ADA/BTC',
          sellAmount: 0,
          sellingPrice: 0.00001159,
          buyingPrice: 0.00001137,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview28',
          description: 'BTC • USD'
        },
        {
          id: 'contract32',
          value: false,
          product: 'BSV/BTC',
          sellAmount: 0,
          sellingPrice: 0.017872579,
          buyingPrice: 0.017850555,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview29',
          description: 'BTC • USD'
        },
      ],
      contracts6: [
        {
          id: 'contract33',
          value: false,
          product: 'BTC/ETH',
          sellAmount: 0,
          sellingPrice: 30.13164116,
          buyingPrice: 30.12931857,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview30',
          description: 'BTC • USD'
        },
        {
          id: 'contract34',
          value: false,
          product: 'USDT/ETH',
          sellAmount: 0,
          sellingPrice: 0.008300133,
          buyingPrice: 0.008289812,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview31',
          description: 'BTC • USD'
        },
        {
          id: 'contract35',
          value: false,
          product: 'LTC/ETH',
          sellAmount: 0,
          sellingPrice: 0.366139936,
          buyingPrice: 0.365725188,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview32',
          description: 'BTC • USD'
        },
        {
          id: 'contract36',
          value: false,
          product: 'EOS/ETH',
          sellAmount: 0,
          sellingPrice: 0.022847663,
          buyingPrice: 0.022660197,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview33',
          description: 'BTC • USD'
        },
        {
          id: 'contract36',
          value: false,
          product: 'XRP/ETH',
          sellAmount: 0,
          sellingPrice: 0.002509228,
          buyingPrice: 0.002498445,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview34',
          description: 'BTC • USD'
        },
        {
          id: 'contract37',
          value: false,
          product: 'DASH/ETH',
          sellAmount: 0,
          sellingPrice: 0.658703496,
          buyingPrice: 0.657376301,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview35',
          description: 'BTC • USD'
        },
        {
          id: 'contract38',
          value: false,
          product: 'BCH/ETH',
          sellAmount: 0,
          sellingPrice: 1.022437891,
          buyingPrice: 1.020447099,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview36',
          description: 'BTC • USD'
        },
        {
          id: 'contract39',
          value: false,
          product: 'BNB/ETH',
          sellAmount: 0,
          sellingPrice: 0.079859815,
          buyingPrice: 0.079816681,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview37',
          description: 'BTC • USD'
        },
        {
          id: 'contract40',
          value: false,
          product: 'ADA/ETH',
          sellAmount: 0,
          sellingPrice: 0.000349218,
          buyingPrice: 0.000342582,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview38',
          description: 'BTC • USD'
        },
        {
          id: 'contract41',
          value: false,
          product: 'BSV/ETH',
          sellAmount: 0,
          sellingPrice: 0.538509394,
          buyingPrice: 0.537845797,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview39',
          description: 'BTC • USD'
        },
      ],
      contracts7: [
        {
          id: 'contract42',
          value: false,
          product: 'BTC/USDT',
          sellAmount: 0,
          sellingPrice: 3632.52,
          buyingPrice: 3632.24,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview1',
          description: 'BTC • USD'
        },
        {
          id: 'contract43',
          value: false,
          product: 'ETH/USDT',
          sellAmount: 0,
          sellingPrice: 120.63,
          buyingPrice: 120.48,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview2',
          description: 'ETH • USD'
        },
        {
          id: 'contract44',
          value: false,
          product: 'LTC/USDT',
          sellAmount: 0,
          sellingPrice: 44.14,
          buyingPrice: 44.09,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview5',
          description: 'LTC • USD'
        },
        {
          id: 'contract45',
          value: false,
          product: 'USDT/BTC',
          sellAmount: 0,
          sellingPrice: 0.000275312,
          buyingPrice: 0.000275291,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview20',
          description: 'BTC • USD'
        },
        {
          id: 'contract46',
          value: false,
          product: 'ETH/BTC',
          sellAmount: 0,
          sellingPrice: 12.53311723,
          buyingPrice: 12.51753265,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview40',
          description: 'BTC • USD'
        },
        {
          id: 'contract47',
          value: false,
          product: 'LTC/BTC',
          sellAmount: 0,
          sellingPrice: 4.586021673,
          buyingPrice: 4.580826814,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview41',
          description: 'BTC • USD'
        },
        {
          id: 'contract48',
          value: false,
          product: 'BTC/ETH',
          sellAmount: 0,
          sellingPrice: 87110.79137,
          buyingPrice: 87104.07674,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview42',
          description: 'BTC • USD'
        },
        {
          id: 'contract49',
          value: false,
          product: 'USDT/ETH',
          sellAmount: 0,
          sellingPrice: 0.008300133,
          buyingPrice: 0.008289812,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview31',
          description: 'BTC • USD'
        },
        {
          id: 'contract50',
          value: false,
          product: 'LTC/ETH',
          sellAmount: 0,
          sellingPrice: 1058.513189,
          buyingPrice: 1057.314149,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview43',
          description: 'BTC • USD'
        },
      ],
      contracts8: [
        {
          id: 'contract51',
          value: false,
          product: 'EOS/USDT',
          sellAmount: 0,
          sellingPrice: 2.7544,
          buyingPrice: 2.7318,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview3',
          description: 'EOS • USD'
        },
        {
          id: 'contract52',
          value: false,
          product: 'XRP/USTD',
          sellAmount: 0,
          sellingPrice: 0.3025,
          buyingPrice: 0.3012,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview16',
          description: 'BTC • USD'
        },
        {
          id: 'contract53',
          value: false,
          product: 'DASH/USDT',
          sellAmount: 0,
          sellingPrice: 79.41,
          buyingPrice: 79.25,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview17',
          description: 'BTC • USD'
        },
        {
          id: 'contract54',
          value: false,
          product: 'EOS/BTC',
          sellAmount: 0,
          sellingPrice: 0.286174402,
          buyingPrice: 0.283826325,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview44',
          description: 'BTC • USD'
        },
        {
          id: 'contract55',
          value: false,
          product: 'XRP/BTC',
          sellAmount: 0,
          sellingPrice: 0.03142890,
          buyingPrice: 0.03129383,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview45',
          description: 'BTC • USD'
        },
        {
          id: 'contract56',
          value: false,
          product: 'DASH/BTC',
          sellAmount: 0,
          sellingPrice: 8.25047533,
          buyingPrice: 8.23385178,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview46',
          description: 'BTC • USD'
        },
        {
          id: 'contract57',
          value: false,
          product: 'EOS/ETH',
          sellAmount: 0,
          sellingPrice: 66.05275779,
          buyingPrice: 65.51079137,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview47',
          description: 'BTC • USD'
        },
        {
          id: 'contract58',
          value: false,
          product: 'XRP/ETH',
          sellAmount: 0,
          sellingPrice: 7.254196643,
          buyingPrice: 7.223021583,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview48',
          description: 'BTC • USD'
        },
        {
          id: 'contract59',
          value: false,
          product: 'DASH/ETH',
          sellAmount: 0,
          sellingPrice: 1904.316547,
          buyingPrice: 1900.479616,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview49',
          description: 'BTC • USD'
        },
      ],
      contracts9: [
        {
          id: 'contract60',
          value: false,
          product: 'BCH/USDT',
          sellAmount: 0,
          sellingPrice: 123.26,
          buyingPrice: 123.02,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview6',
          description: 'BCH • USD'
        },
        {
          id: 'contract61',
          value: false,
          product: 'BNB/USDT',
          sellAmount: 0,
          sellingPrice: 9.6275,
          buyingPrice: 9.6223,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview18',
          description: 'BTC • USD'
        }, 
        {
          id: 'contract62',
          value: false,
          product: 'ADA/USDT',
          sellAmount: 0,
          sellingPrice: 0.0421,
          buyingPrice: 0.0413,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview19',
          description: 'BTC • USD'
        },
        {
          id: 'contract63',
          value: false,
          product: 'BSV/USDT',
          sellAmount: 0,
          sellingPrice: 64.92,
          buyingPrice: 64.84,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview8',
          description: 'BSV • USD'
        },
        {
          id: 'contract64',
          value: false,
          product: 'BCH/BTC',
          sellAmount: 0,
          sellingPrice: 12.80636682,
          buyingPrice: 12.7814315,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview50',
          description: 'BTC • USD'
        },
        {
          id: 'contract65',
          value: false,
          product: 'BNB/BTC',
          sellAmount: 0,
          sellingPrice: 1.000270133,
          buyingPrice: 0.999729867,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview51',
          description: 'BTC • USD'
        },
        {
          id: 'contract66',
          value: false,
          product: 'ADA/BTC',
          sellAmount: 0,
          sellingPrice: 0.00437407,
          buyingPrice: 0.00429095,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview52',
          description: 'BTC • USD'
        },
        {
          id: 'contract67',
          value: false,
          product: 'BSV/BTC',
          sellAmount: 0,
          sellingPrice: 6.745005143,
          buyingPrice: 6.736693368,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview53',
          description: 'BTC • USD'
        },
        {
          id: 'contract68',
          value: false,
          product: 'BCH/ETH',
          sellAmount: 0,
          sellingPrice: 2955.8753,
          buyingPrice: 2950.119904,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview54',
          description: 'BTC • USD'
        },
        {
          id: 'contract69',
          value: false,
          product: 'BNB/ETH',
          sellAmount: 0,
          sellingPrice: 230.8752998,
          buyingPrice: 230.7505995,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview55',
          description: 'BTC • USD'
        },
        {
          id: 'contract70',
          value: false,
          product: 'ADA/ETH',
          sellAmount: 0,
          sellingPrice: 1.009592326,
          buyingPrice: 0.990407674,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview56',
          description: 'BTC • USD'
        },
        {
          id: 'contract71',
          value: false,
          product: 'BSV/ETH',
          sellAmount: 0,
          sellingPrice: 1556.834532,
          buyingPrice: 1554.916067,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview57',
          description: 'BTC • USD'
        },
      ],
      contracts10: [
        {
          id: 'contract72',
          value: false,
          product: '美元指数',
          sellAmount: 0,
          sellingPrice: 96.6574,
          buyingPrice: 95.6689,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview58',
          description: 'BTC • USD'
        },
        {
          id: 'contract73',
          value: false,
          product: '美元人民币',
          sellAmount: 0,
          sellingPrice: 6.9892,
          buyingPrice: 6.7892,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview59',
          description: 'BTC • USD'
        },
        {
          id: 'contract74',
          value: false,
          product: '欧元美元',
          sellAmount: 0,
          sellingPrice: 1.1311,
          buyingPrice: 1.131,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview60',
          description: 'BTC • USD'
        },
        {
          id: 'contract75',
          value: false,
          product: '欧元美元',
          sellAmount: 0,
          sellingPrice: 1.1311,
          buyingPrice: 1.131,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview60',
          description: 'BTC • USD'
        },
        {
          id: 'contract76',
          value: false,
          product: '英镑美元',
          sellAmount: 0,
          sellingPrice: 1.2899,
          buyingPrice: 1.2888,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview61',
          description: 'BTC • USD'
        },
        {
          id: 'contract77',
          value: false,
          product: '美元日元',
          sellAmount: 0,
          sellingPrice: 110.28,
          buyingPrice: 110.11,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview62',
          description: 'BTC • USD'
        },
        {
          id: 'contract78',
          value: false,
          product: '美元挪威',
          sellAmount: 0,
          sellingPrice: 8.6817,
          buyingPrice: 8.6811,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview63',
          description: 'BTC • USD'
        },
        {
          id: 'contract79',
          value: false,
          product: '美元丹麦克朗',
          sellAmount: 0,
          sellingPrice: 6.5986,
          buyingPrice: 6.5981,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview64',
          description: 'BTC • USD'
        },
        {
          id: 'contract79',
          value: false,
          product: '美元南非兰特',
          sellAmount: 0,
          sellingPrice: 13.7352,
          buyingPrice: 13.7351,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview65',
          description: 'BTC • USD'
        },
        {
          id: 'contract80',
          value: false,
          product: '美元土耳其里拉',
          sellAmount: 0,
          sellingPrice: 5.265,
          buyingPrice: 5.255,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview66',
          description: 'BTC • USD'
        },
        {
          id: 'contract81',
          value: false,
          product: '美元墨西哥比索',
          sellAmount: 0,
          sellingPrice: 19.0928,
          buyingPrice: 19.0025,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview67',
          description: 'BTC • USD'
        },
        {
          id: 'contract82',
          value: false,
          product: '欧元美元',
          sellAmount: 0,
          sellingPrice: 0.7075,
          buyingPrice: 0.07055,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview68',
          description: 'BTC • USD'
        },
        {
          id: 'contract83',
          value: false,
          product: '美元人民币离岸',
          sellAmount: 0,
          sellingPrice: 6.7947,
          buyingPrice: 6.7549,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview69',
          description: 'BTC • USD'
        },
        {
          id: 'contract84',
          value: false,
          product: '美元瑞典',
          sellAmount: 0,
          sellingPrice: 9.2692,
          buyingPrice: 9.2691,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview70',
          description: 'BTC • USD'
        },
        {
          id: 'contract85',
          value: false,
          product: '纽元美元',
          sellAmount: 0,
          sellingPrice: 0.6746,
          buyingPrice: 0.6722,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview71',
          description: 'BTC • USD'
        },
        {
          id: 'contract86',
          value: false,
          product: '美元新加坡元',
          sellAmount: 0,
          sellingPrice: 1.3585,
          buyingPrice: 1.3511,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview72',
          description: 'BTC • USD'
        },
        {
          id: 'contract87',
          value: false,
          product: '美元加元',
          sellAmount: 0,
          sellingPrice: 1.3279,
          buyingPrice: 1.3211,
          buyAmount: 0,
          marketPrice: 'TSE',
          percent: '0.00%',
          fallAndRaise: 0.00,
          overviewId: 'overview73',
          description: 'BTC • USD'
        },
      ]
    }
  },
}

// getters
const getters = {
  selectedContract: state => {
    const result = state.contracts.data[state.selectedContractsId].find(contract => contract.id === state.selectedContractId);
    return result;
  }
}

// actions
const actions = {
}

// mutations
const mutations = {
  selectContractsId(state, contractsId) {
    state.selectedContractsId = contractsId;
  },
  selectContract(state, contractId) {
    state.selectedContractId = contractId;
  }
}

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
